"""Add ledger, unconfirmed_balance, and UI config

Revision ID: 4911cf6e5801
Revises: 
Create Date: 2026-03-22 20:43:46.122480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4911cf6e5801'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount_ltc', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_user_id', 'ledger', ['user_id'], unique=False)
    op.add_column('system_config', sa.Column('panel_message_ids', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('unconfirmed_balance', sa.Numeric(precision=16, scale=8), nullable=True))
    op.create_unique_constraint(None, 'users', ['deposit_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'unconfirmed_balance')
    op.drop_column('system_config', 'panel_message_ids')
    op.drop_index('idx_ledger_user_id', table_name='ledger')
    op.drop_table('ledger')
    # ### end Alembic commands ###
